export const EMAIL_AUTH_SIGNUP_REQUEST = "SIGNUP_02/SIGNUP/REQUEST";
export const EMAIL_AUTH_SIGNUP_SUCCESS = "SIGNUP_02/SIGNUP/SUCCESS";
export const EMAIL_AUTH_SIGNUP_ERROR = "SIGNUP_02/SIGNUP/ERROR";

export const EMAIL_AUTH_LOGIN_REQUEST = "SIGNUP_02/LOGIN/REQUEST";
export const EMAIL_AUTH_LOGIN_SUCCESS = "SIGNUP_02/LOGIN/SUCCESS";
export const EMAIL_AUTH_LOGIN_ERROR = "SIGNUP_02/LOGIN/ERROR";

// does not follow the patern REQUERST/SUCCESS/ERROR since it is syncronus action
export const EMAIL_AUTH_LOGOUT = "SIGNUP_02/LOGOUT";

export const EMAIL_AUTH_PASSWORD_RECOVER_REQUEST =
  "SIGNUP_02/PASSORD_RECOVER/REQUEST";
export const EMAIL_AUTH_PASSWORD_RECOVER_SUCCESS =
  "SIGNUP_02/PASSORD_RECOVER/SUCCESS";
export const EMAIL_AUTH_PASSWORD_RECOVER_ERROR =
  "SIGNUP_02/PASSORD_RECOVER/ERROR";